using System;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public class Data : MonoBehaviour
{
    //Stores data and persists
    public static Data Instance { get; private set; }

    public string playerName;

    public int playerLives;

    public float carSpeed;

    public float gameSpeed;

    public int score = 0;

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            Destroy(gameObject);
        }
    }

    private void Update()
    {
        Time.timeScale = carSpeed;
    }
}
